name: save images
on:
  schedule:
    - cron: '35 13 * 5-10 *'
    - cron: '35 15 * 5-10 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: save images
      CI_COMMIT_AUTHOR: Github Actions
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Create now.json
      run: echo "[\"`TZ=Asia/Taipei date -Isecond`\"]" > docs/now.json
    - name: install puppeteer
      run: npm ci
    - name: save images
      run: node ./puppeteer/above500.js
      working-directory: ./
    - name: commit and push
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "${{ secrets.MY_SECRET_EMAIL}}"
        git add .
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
